variables:
  PEP8_CONFIG_FILE: .flake8
  PEP8_DOCKER_IMAGE: alpine/flake8

stages:
  - lint

code-style:
  stage: lint
  script:
    - docker run -it --rm $(pwd):/apps $PEP8_DOCKER_IMAGE --config $PEP8_CONFIG_FILE
